---
- name: Python dependencies are installed.
  sudo: yes
  tags:
    - python
  apt:
    name={{ item }}
    force=yes
    update_cache=yes
    force=yes
  with_items: python_deps

- name: Haskell dependencies are installed.
  sudo: yes
  tags:
    - haskell
  apt:
    name={{ item }}
    force=yes
    update_cache=yes
    force=yes
  with_items: haskell_deps

- name: R dependencies are installed.
  sudo: yes
  tags:
    - rstats
  apt:
    name={{ item }}
    force=yes
    update_cache=yes
    force=yes
  with_items: r_deps

- name: Cabal cache is updated and latest version is installed.
  remote_user: pair
  command: "{{item}}"
  tags:
    - haskell
  with_items:
    - cabal update
    - cabal install -j cabal-install

- name: Newest Cabal is symlinked to /usr/bin/cabal.
  sudo: yes
  tags:
    - haskell
  file:
    src=/home/pair/.cabal/bin/cabal
    dest=/usr/bin/cabal
    force=yes
    state=link

- name: pair has cabal permissions.
  sudo: yes
  tags:
    - haskell
  command: chown pair /usr/bin/cabal

- name: Haskell dev tools are installed.
  command: "{{item}}"
  remote_user: pair
  tags:
    - haskell
  with_items:
    - cabal install -j hlint
    - cabal install -j ghc-mod
    - cabal install -j pointfree
    - cabal install -j hasktags

- name: ipython profile exists.
  remote_user: pair
  tags:
    - python
  command: ipython profile create

- name: ipython doesn't confirm exit.
  remote_user: pair
  tags:
    - python
  lineinfile:
    dest=/home/pair/.ipython/profile_default/ipython_config.py
    regexp=".*confirm_exit"
    line="c.TerminalInteractiveShell.confirm_exit = False"
    state=present

