---
- name: apt sources are updated.
  sudo: yes
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Wheezy sources are absent.
  sudo: yes
  apt_repository: repo="{{item}}" state=absent
  with_items:
    - deb {{ debian_mirror }}/debian/ wheezy main
    - deb-src {{ debian_mirror }}/debian/ wheezy main
    - deb {{ debian_mirror }}/debian-security/ wheezy/updates main
    - deb-src {{ debian_mirror }}/debian-security/ wheezy/updates main
    - deb {{ debian_mirror }}/debian/ wheezy-updates main
    - deb-src {{ debian_mirror }}/debian/ wheezy-updates main

- name: Sid sources are present.
  sudo: yes
  apt_repository:
    repo="{{item}}"
    state=present
  with_items:
    - deb {{ debian_mirror }}/debian/ sid main
    - deb-src {{ debian_mirror }}/debian/ sid main

- name: apt sources are upgraded.
  sudo: yes
  apt:
    upgrade=dist
    cache_valid_time=3600

- name: General dependencies are installed.
  sudo: yes
  apt:
    name={{ item }}
    force=yes
    update_cache=yes
    cache_valid_time=3600
    force=yes
  with_items:
    general_deps

- name: pair is a sudoer.
  sudo: yes
  user:
    name=pair
    groups=sudo
    append=yes
    state=present
    shell=/bin/bash
    password={{ pair_crypted_password }}

- name: pair has an authorized key.
  sudo: yes
  authorized_key:
    user=pair
    key="{{item}}"
    state=present
  with_file:                      
    - "{{ my_public_key_path }}"

- name: Password authentication is permitted.
  sudo: yes
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^#*PasswordAuthentication"
    line="PasswordAuthentication yes"
    state=present
  notify:
    - restart sshd

- name: ssh-agent forwarding is not allowed.
  sudo: yes
  lineinfile:
    dest=/etc/ssh/sshd_config
    line="AllowAgentForwarding no"
    state=present
  notify:
    - restart sshd

- name: .dotfiles repo is present and up-to-date.
  remote_user: pair
  git:
    repo=https://github.com/jtobin/.dotfiles
    dest=/home/pair/.dotfiles
    accept_hostkey=yes

- name: .dotfiles submodules are initialized and up to date.
  remote_user: pair
  command: "{{item}} chdir=/home/pair/.dotfiles"
  with_items:
    - git submodule init
    - git submodule update

- name: dotfiles are linked appropriately.
  remote_user: pair
  file:
    src=/home/pair/.dotfiles/{{ item.src }}
    dest=/home/pair/{{ item.dest }}
    force=yes
    state=link
  with_items:
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'vimrc', dest: '.vimrc' }
    - { src: 'vim', dest: '.vim' }
    - { src: 'tmux.conf', dest: '.tmux.conf' }

- name: tmux status-bg is blue.
  remote_user: pair
  lineinfile:
    dest=/home/pair/.tmux.conf
    regexp="status-bg"
    line="set -g status-bg blue"
    state=present

- name: vimproc.vim is installed.
  remote_user: pair
  command: make chdir=/home/pair/.dotfiles/vim/bundle/vimproc

- name: tmux session exists.
  remote_user: pair
  command: tmux new-session -d -s pair
  ignore_errors: yes

